### ISSUE TITLE
Abandon ship?

### ISSUE THREAD

**Issue by HughParsonage** [ropensci-archive/ozdata#5]
Are we abandoning this repository and moving the work to datagovau ?

PS: Monash said no to a new computer -- they need a few days' notice. I'll try to get down for lunch tomorrow! Miss you guys already!

**Comment by ellisp** [comment]
I think so for the data.gov.au part.  @thejholloway and I have made good progress on starting that up as an R package.

We could keep the ozdata repository going though for eventually being a portmaneau package.
